FROM node:12 as builder

WORKDIR /client

COPY package.json ./package.json
RUN npm install
COPY . .

RUN npm run build

FROM nginx:latest
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /client/build /usr/share/nginx/html
COPY --from=builder /client/build /client/build

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
