# Generated by Django 3.2.3 on 2021-05-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '__first__'),
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='carted_users', to='recommend.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='users', to='recommend.Keyword'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_items',
            field=models.ManyToManyField(blank=True, related_name='likes_users', to='recommend.Item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
    ]
