# Generated by Django 3.2.3 on 2021-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '__first__'),
        ('accounts', '0003_auto_20210531_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='recommend.Item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_items',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='recommend.Item'),
        ),
    ]
