FROM python:3

# create the app user
RUN addgroup elice && adduser asap --group elice

# create the appropriate directories
ENV APP_HOME=/backend
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# install dependencies
RUN apt update && apt install libpq-dev
COPY requirements.txt $APP_HOME
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R asap:elice $APP_HOME

# change to the app user
USER asap
