# Generated by Django 3.2.3 on 2021-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('asin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('price', models.FloatField(null=True)),
                ('is_women', models.BooleanField()),
                ('category', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('outer', 'outer'), ('set', 'set'), ('sport', 'sport'), ('etc', 'etc'), ('shoes', 'shoes'), ('bag', 'bag'), ('accessaries', 'accessaries')], max_length=15)),
                ('keywords', models.ManyToManyField(related_name='items', to='recommend.Keyword')),
            ],
        ),
    ]
