# Generated by Django 3.2.3 on 2021-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('outer', 'outer'), ('set', 'set'), ('sport', 'sport'), ('etc', 'etc'), ('shoes', 'shoes'), ('bag', 'bag'), ('accessories', 'accessories')], max_length=15),
        ),
    ]
