export const Auth = {
  USER_LOADING: 'USER_LOADING',
  USER_LOADED: 'USER_LOADED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  CLEAR_USER: 'CLEAR_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
};

export const ProductActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_CATEGORY: 'SET_CATEGORY',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  SELECT_PRODUCT_ID: 'SELECT_PRODUCT_ID',
  UNSELECT_PRODUCT: 'UNSELECT_PRODUCT',
  UNSELECT_PRODUCT_ID: 'UNSELECT_PRODUCT_ID',
  SET_LIKES: 'SET_LIKES',
  DELETE_LIKES: 'DELETE_LIKES',
  LOAD_LIKES: 'LOAD_LIKES',
  ADD_TO_LIKES: 'ADD_TO_LIKES',
  UNDO_LIKES: 'UNDO_LIKES',
  SET_CART: 'SET_CART',
  DELETE_CART: 'DELETE_CART',
  LOAD_CART: 'LOAD_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  UNDO_CART: 'UNDO_CART',
  SET_ORDER_DETAILS: 'SET_ORDER_DETAILS',
  SHOW_MODAL: 'SHOW_MODAL',
  RESET_MODAL: 'RESET_MODAL',
  ORDER_REQUEST: 'ORDER_REQUEST',
};

export const UserSelectTypes = {
  SELECT_GENDER: 'SELECT_GENDER',
  SELECT_CATEGORIES: 'SELECT_CATEGORIES',
  SET_KEYWORDS: 'SET_KEYWORDS',
  SELECT_KEYWORDS: 'SELECT_KEYWORDS',
  UNSELECT_KEYWORDS: 'UNSELECT_KEYWORDS',
  SET_RECOMMEND: 'SET_RECOMMEND',
};
