export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_USER = 'CLEAR_USER';

export const ProductActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_CATEGORY: 'SET_CATEGORY',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  SET_LIKES: 'SET_LIKES',
  SELECT_PRODUCT_ID: 'SELECT_PRODUCT_ID',
  UNSELECT_PRODUCT: 'UNSELECT_PRODUCT',
  UNSELECT_PRODUCT_ID: 'UNSELECT_PRODUCT_ID',
  LIKE_PRODUCT: 'LIKE_PRODUCT',
  LIKE_SUCCESS: 'LIKE_SUCCESS',
  LIKE_ALREADY: 'LIKE_ALREADY',
  DELETE_LIKES: 'DELETE_LIKES',
  SET_CART: 'SET_CART',
  DELETE_CART: 'DELETE_CART',
  SET_ORDER_DETAILS: 'SET_ORDER_DETAILS',
  SHOW_MODAL: 'SHOW_MODAL',
  RESET_MODAL: 'RESET_MODAL',
  ORDER_REQUEST: 'ORDER_REQUEST',
  LOAD_LIKES: 'LOAD_LIKES',
  ADD_TO_LIKES: 'ADD_TO_LIKES',
  UNDO_LIKES: 'UNDO_LIKES',
};

export const SET_USERINFO = 'SET_USERINFO';
