export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_USER = 'CLEAR_USER';

export const ProductActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  LIKE_PRODUCT: 'LIKE_PRODUCT',
  LIKE_SUCCESS: 'LIKE_SUCCESS',
  LIKE_ALREADY: 'LIKE_ALREADY',
  SHOW_MODAL: 'SHOW_MODAL',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_CART: 'SET_CART',
  SET_LIKES: 'SET_LIKES',
  SET_ORDER_DETAILS: 'SET_ORDER_DETAILS',
};
