# Generated by Django 3.2.3 on 2021-05-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='test product name')),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='test user name')),
                ('bag', models.ManyToManyField(related_name='test_bag', to='mypage.TestProduct')),
                ('history', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mypage.testproduct')),
                ('wish', models.ManyToManyField(related_name='test_wish', to='mypage.TestProduct')),
            ],
        ),
    ]
