# Generated by Django 3.2.3 on 2021-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='test product name')),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='test user name')),
                ('bags', models.ManyToManyField(related_name='test_bags', to='mypage.TestProduct')),
                ('likes', models.ManyToManyField(related_name='test_likes', to='mypage.TestProduct')),
            ],
        ),
    ]
