# Generated by Django 3.2.3 on 2021-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testuser',
            name='history',
        ),
        migrations.AddField(
            model_name='testuser',
            name='buy',
            field=models.ManyToManyField(related_name='test_buy', to='mypage.TestProduct'),
        ),
    ]
